# Generated by Django 6.0.5 on 2026-05-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_aboutcontent_contactmessage_galleryimage_homefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('sports', 'Sports'), ('scientific', 'Scientific')], default='cultural', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('poster', models.ImageField(blank=True, upload_to='prizes/posters/')),
                ('announcement_date', models.DateField()),
                ('announcement_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', '-announcement_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='infoupdate',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional link to an outside website'),
        ),
        migrations.AddField(
            model_name='infoupdate',
            name='pdf',
            field=models.FileField(blank=True, help_text='Optional PDF upload', upload_to='info/pdfs/'),
        ),
        migrations.CreateModel(
            name='PrizeWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prize_label', models.CharField(help_text='Example: 1st Prize, 2nd Prize, Best Performer', max_length=50)),
                ('winner_type', models.CharField(choices=[('solo', 'Solo winner'), ('team', 'Batch/Team winner')], default='solo', max_length=10)),
                ('winner_name', models.CharField(help_text='Student name, batch name, or team name', max_length=140)),
                ('batch_or_team', models.CharField(blank=True, help_text='Example: Batch 2026 or Team Incendios', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='studentapp.prizecompetition')),
            ],
            options={
                'ordering': ['order', 'prize_label'],
            },
        ),
    ]
