# Generated by Django 6.0.5 on 2026-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_prizecompetition_infoupdate_external_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
    ]
