# Generated by Django 6.0.6 on 2026-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_remove_unique_event_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Use line breaks for multiple paragraphs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
