# Generated by Django 6.0.6 on 2026-06-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#ffcc00', help_text='Use a hex color such as #ffcc00.', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='clubs/')),
                ('founder', models.CharField(max_length=120)),
                ('starting_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(),
        ),
    ]
