# Generated by Django 6.0.6 on 2026-06-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0013_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='drive_link',
            field=models.URLField(blank=True),
        ),
    ]
